AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    21d977c7-4060-4ae2-98d0-c02509c6370a:
      size:
        width: 60
        height: 60
      position:
        x: 520
        'y': 60
      z: 0
      embeds: []
Resources:
  DiscussionBoardTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: CourseDiscussionBoards
      AttributeDefinitions:
        - AttributeName: CourseID
          AttributeType: S
      KeySchema:
        - AttributeName: CourseID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 21d977c7-4060-4ae2-98d0-c02509c6370a